### PR TITLE
Address #17 by filtering Macro and Label images from SVS files

### LINKED ISSUE #17: Aperio SVS Files Load Unnecessary Macro Thumbnails and Labels Which Renders Incorrectly
The Aperio file format specification for SVS specifically recommends stripping two components from SVS files before rendering called `macro` and `label` which refer to additional slide information and thumbnails which can mess up tiled rendering of the actual slide information:

> Optionally at the end of an SVS file there may be a slide label image, which is a low resolution
picture taken of the slide’s label, and/or a macro camera image, which is a low resolution picture
taken of the entire slide. The label and macro images are always stripped.[^1]

I'm going to open a pull request shortly to address this, but first I have to find some publicly available data to test with that can be shared.

[^1]: [Aperio Digital Slide Interchange Format (SVS) pg 14](https://web.archive.org/web/20120420105738/http://www.aperio.com/documents/api/Aperio_Digital_Slides_and_Third-party_data_interchange.pdf)

### PR DESCRIPTION
**Pull request by mdushkoff**
This should fix #17 by filtering out macro & label images from SVS slides.  Currently looking for publicly available test data to validate this change.

### CODE REVIEW

**Comment by abiswas97** [comment]
@mdushkoff instead of filtering out the macro and label, what do you think of separating them into different image sets? Since the code currently groups images by aspect ratio and maintains them as separate image sets - which then get flagged as tiled or not. I'm assuming the issue you're facing is an image where the aspect ratio of the macro or label matches the regular tiled image, causing it to accidentally be grouped with the pyramid. 

It might be desirable to keep track of the macro or label image for rendering elsewhere. 

@pearcetm what do you think?

**Comment by mdushkoff** [comment]
Strangely, the scenario that prompted this was actually a case where the macros and labels had completely different aspect ratios from the real tile images and were still getting rendered over the real slide data.  It could definitely be useful to keep the macro and label images for rendering elsewhere, but they should definitely be excluded from the pyramid.  If they were kept what would be a good way to represent them to the user, @abiswas97 ?

**Comment by pearcetm** [comment]
> Strangely, the scenario that prompted this was actually a case where the macros and labels had completely different aspect ratios from the real tile images and were still getting rendered over the real slide data.

That's strange. When I use the [demo page](https://pearcetm.github.io/GeoTIFFTileSource/demo/demo.html) to open an SVS file, it opens the images in sequence mode in OpenSeadragon. The image pyramid works correctly as the first image:
image

If you use the button to navigate to the next pages, you'll see the macro and then the label:
image

Is the demo page giving you the same results with your SVS files as your local build?

**Comment by mdushkoff** [comment]
With this branch, the demo page displays the slides correctly and only the slides, no macro/label.

**Comment by mdushkoff** [comment]
Upon further inspection @abiswas97 was correct about the aspect ratio being relatively close in that they fall within the current tolerance, however they're at the very far end of this.  I've modified the existing filter to include information about the image description.  With this change, the label/macro images are preserved as separate sets as mentioned above, but never included in the pyramid.

File: src/main.js [hunk 1]
```diff
@@ -137,10 +137,15 @@ export const enableGeoTIFFTileSource = (OpenSeadragon) => {
           // find unique aspect ratios (with tolerance to account for rounding)
           const tolerance = 0.015;
 
+          // Organize images into sets based on aspect ratio as well as
+          // macro thumbnails and labels according to the Aperio SVS format:
+          //   https://web.archive.org/web/20120420105738/http://www.aperio.com/documents/api/Aperio_Digital_Slides_and_Third-party_data_interchange.pdf (pg 14)
           const aspectRatioSets = images.reduce((accumulator, image) => {
             const r = image.getWidth() / image.getHeight();
+            const s = image.fileDirectory.ImageDescription.split("\n")[1];
```
Comment (pearcetm) [inline src/main.js:145]: Is `ImageDescription` guaranteed to exist as a field within `fileDirectory` for all TIFF files? If not (or if it is missing even if against spec) this line will break the plugin. I think it would be smart to do something like:

```
if(image.fileDirectory.ImageDescription){
...
}
```

**Comment by pearcetm** [comment]
> Upon further inspection @abiswas97 was correct about the aspect ratio being relatively close in that they fall within the current tolerance,

I figured this must be true. With the wide variety of TIFF files out there, I tried to detect which pages belong in a pyramid automatically, but obviously this approach can fail in edge cases like the one you found.

I'm definitely open to checking for special cases we know about in advance (like SVS files). Let's just make it as robust as possible while we're making the change.

File: src/main.js (hunk 1 above)
Comment (mdushkoff) [reply src/main.js:145]: That is a fair check, I'll add this.  I am certain there are remote possibilities of edge cases where it is missing.

**Comment by mdushkoff** [comment]
I've included your suggestions above to the latest.

Speaking of robustness, do you believe that there should be additional checks based on the file type itself or should they all be handled in the mapping function regardless?  I'm not sure how likely or if ever it would be the case that a non-SVS file implements a label/macro that is expected to be part of the tileset.

**Comment by abiswas97** [comment]
@mdushkoff My setup is similar to the demo page, where I use OSD's sequence mode to allow the user to view supplementary images if present. 

I think having a check beforehand might help, since having file type specific context can be useful for the entire class. Maybe an ImageReader class that can have its own pre/post processing step when determining tilesets?

As for how likely other file types are to have a macro, I've noticed that most tiff based format (svs, tiff, ome.tiff, qptiff etc) do include one

**Comment by mdushkoff** [comment]
@abiswas97 In those tiff based formats, do you know if it is expected that the macro is a separate image set to the pyramid, or is that an SVS-specific case to keep it separate?

**Comment by pearcetm** [comment]
> @abiswas97 In those tiff based formats, do you know if it is expected that the macro is a separate image set to the pyramid, or is that an SVS-specific case to keep it separate?

Although I'm not away of the other TIFF formats that include macro images, I suspect that they, like SVS, would not expect the macro to be part of the main image pyramid.

**Comment by pearcetm** [comment]
This is looking good to me, @mdushkoff.

@abiswas97 did you have any further thoughts, or should I go ahead and merge this as-is?

**Comment by pearcetm** [comment]
Checking back in on this @abiswas97 and @mdushkoff. Do you think this is ready to merge?

**Comment by mdushkoff** [comment]
I'd say so, unless there's any other concerns.

**Comment by abiswas97** [comment]
@pearcetm @mdushkoff just getting to this - sorry for being late to this discussion. 

In images where I've noticed macro images, they've been separate images independent of the main image pyramid. So far I've seen this in tiff, ome.tiff, qptif, and svs (mostly svs). I'll see if I can find an open source example to attach here. 

Given how freeform TIFF is, maybe some won't adhere to this standard? But maybe we can take it into account if we get pointed at an example from any future issue?

I think this looks good to merge. My only nit would be some clarity what `s` is, but this should be a very helpful change!

**Comment by pearcetm** [comment]
Thanks for this fix! Merging now.
